apiVersion: v1
kind: Service
metadata:
  name: html-service
  labels:
    app: html-app
spec:
  selector:
    app: html-app
  type: NodePort
  ports: 
  - nodePort: 31000
    port: 80
    targetPort: 80