apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-html-pvc1
  labels:
    name: php-pvc1
spec:
  accessModes:
   - ReadWriteOnce
  resources:  
    requests:
      storage: 2Gi