apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    app: php
spec:
  selector:
    app: php-app
  type: NodePort
  ports: 
  - nodePort: 31000
    port: 80
    targetPort: 80