apiVersion: v1
kind: Pod
metadata:
  name: php-pod
  labels:
    app: php-app
spec:
  containers:
      - name: php
        image: vimal13/apache-webserver-php
        ports:
        - containerPort: 80
        volumeMounts:
        - name: php-vol1
          mountPath: /var/www/html
  volumes:
  - name: php-vol1
    persistentVolumeClaim:
       claimName: php-html-pvc1
  