apiVersion: v1
kind: Pod
metadata:
  name: html-pod
  labels:
    app: html-app
spec:
  containers:
      - name: httpd
        image: ravi10malvia/myhttpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-vol1
          mountPath: /var/www/html
  volumes:
  - name: html-vol1
    persistentVolumeClaim:
       claimName: php-html-pvc1
  